name: data_accessor_dev
channels:
  - conda-forge
  - nodefaults

# env includes all development dependencies
dependencies:
  - python >=3.11

  # For data processing
  - pandas
  - xarray
  - rioxarray
  - dask
  - geopandas

  # For API access and data formats
  - cdsapi
  - fsspec
  - s3fs
  - cfgrib
  - eccodes
  - pyarrow
  - zarr
  - h5netcdf
  - openpyxl

# Dev tools: Language Server Protocol (LSP) (Optional), for:
  - python-lsp-server # LSP extension for Python (pylsp), including:
  - pylsp-mypy  # MyPy type checking for Python >=3.7.
  - pytest # for running our /testing suite
  - pre-commit # for running our the pre-commit hooks

  # Package management
  - conda
  - conda-build # to self install library
  - mamba
  - conda-libmamba-solver  # Faster env solver, https://conda.github.io/conda-libmamba-solver/
  - pip
