name: xarray_data_accessor_env
channels:
  - conda-forge
  - pyviz
  - nodefaults

dependencies:
  - python >=3.10

  # For data processing 
  - pandas
  - xarray
  - rioxarray
  - dask
  - geopandas

  # For API access and data formats
  - cdsapi
  - fsspec
  - s3fs
  - cfgrib
  - eccodes
  - pyarrow
  - zarr
  - h5netcdf

  # Interactivity & Visualization (optional, but required for viz)
  - jupyterlab
  - ipympl
  - nodejs
  - cartopy

  # get holoviews libs from pyviz
  - holoviews
  - hvplot
  - geoviews

# Dev tools: Language Server Protocol (LSP) (Optional), for:
  - python-lsp-server # LSP extension for Python (pylsp), including:
  - pylsp-mypy  # MyPy type checking for Python >=3.7.
  - jupyterlab-lsp # Provides both server extension and lab extension
  - pytest # for running our /testing suite

  # Package management
  - conda
  - conda-build # to self install library
  - mamba
  - conda-libmamba-solver  # Faster env solver, https://conda.github.io/conda-libmamba-solver/
  - pip


