name: data_accessor_full
channels:
  - conda-forge
  - nodefaults

# full env includes all dependencies for viz
dependencies:
  - python >=3.11

  # For data processing
  - pandas
  - xarray
  - rioxarray
  - dask
  - geopandas

  # For API access and data formats
  - cdsapi  # Copernicus Climate Data Store (CDS) API
  - fsspec
  - s3fs
  - cfgrib
  - eccodes
  - pyarrow
  - zarr
  - h5netcdf
  - openpyxl
  - metpy
  - pysheds

  # Interactivity & Visualization (optional, but required for viz)
  - jupyterlab
  - ipympl
  - nodejs
  - cartopy
  - holoviews >=1.12.0
  - hvplot
  - geoviews >=1.6.2 # pinned to avoid this issue: https://github.com/holoviz/geoviews/issues/334

  # Dev tools: Language Server Protocol (LSP) (Optional), for:
  - python-lsp-server # LSP extension for Python (pylsp), including:
  - pylsp-mypy  # MyPy type checking for Python >=3.7.
  - jupyterlab-lsp # Provides both server extension and lab extension

  # Package management
  - conda
  - conda-build # to self install library
  - mamba
  - conda-libmamba-solver  # Faster env solver, https://conda.github.io/conda-libmamba-solver/
  # PIP install requirements only if it is not possible with conda
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment
  - pip
  - pip:
    # - fcpgtools # Holding until fcpgtools supports Py 3.11
